#ifndef NXOpen_CAM_DMTOOLPOSITION_HXX_INCLUDED
#define NXOpen_CAM_DMTOOLPOSITION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAM_DmToolPosition.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAM_DPMItpBuilder.hxx>
#include <NXOpen/CAM_DmToolPosition.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_cam_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAM
    {
        class DmToolPosition;
    }
    namespace CAM
    {
        class _DmToolPositionBuilder;
        class DmToolPositionImpl;
        /** Represents a streamline tool position builder  <br> This is an abstract class and cannot be instantiated.  <br> 
         <br>  Created in NX10.0.1.  <br>  
        */
        class NXOPENCPP_CAMEXPORT  DmToolPosition : public NXOpen::TaggedObject
        {
            private: DmToolPositionImpl * m_dmtoolposition_impl;
            private: friend class  _DmToolPositionBuilder;
            protected: DmToolPosition();
            public: ~DmToolPosition();
            /**Returns  the tool position 
             <br>  Created in NX10.0.1.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAM::DPMItpBuilder::ToolPositionOption ToolPosition
            (
            );
            /**Sets  the tool position 
             <br>  Created in NX10.0.1.  <br>  
             <br> License requirements : cam_base ("CAM BASE") */
            public: void SetToolPosition
            (
                NXOpen::CAM::DPMItpBuilder::ToolPositionOption toolPosition /** the tool position value */
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
