#ifndef NXOpen_MECHANICALROUTING_PATHSTOCKPREFERENCEBUILDER_HXX_INCLUDED
#define NXOpen_MECHANICALROUTING_PATHSTOCKPREFERENCEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MechanicalRouting_PathStockPreferenceBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/MechanicalRouting_PathStockPreferenceBuilder.hxx>
#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_mechanicalrouting_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MechanicalRouting
    {
        class PathStockPreferenceBuilder;
    }
    class Expression;
    namespace GeometricUtilities
    {
        class IComponentBuilder;
    }
    class NXObject;
    namespace MechanicalRouting
    {
        class _PathStockPreferenceBuilderBuilder;
        class PathStockPreferenceBuilderImpl;
        /** Assigns stocks to segments based on user's criteria and the current default stock.  
         <br>  Created in NX11.0.0.  <br>  
        */
        class NXOPENCPP_MECHANICALROUTINGEXPORT  PathStockPreferenceBuilder : public NXOpen::TaggedObject, public virtual NXOpen::GeometricUtilities::IComponentBuilder
        {
            /** Determines the type of stock being assigned. */
            public: enum AssignStockType
            {
                AssignStockTypeStock/** Default stock type.            */,
                AssignStockTypeOverstock/** Overstock stock type.           */
            };

            /** Determines the type of sub stock being assigned. This is only valid when Stock type is 'Stock' */
            public: enum AssignStockSubType
            {
                AssignStockSubTypeStock/** Default stock subtype.             */,
                AssignStockSubTypeSpaceReservation/** Space Reservation stock subtype.   */
            };

            /** Determines how to choose which stock to assign. */
            public: enum AssignMethod
            {
                AssignMethodNone/** No Stock. */,
                AssignMethodFromStartObject/** Finds a stock based off of the
                                                                               default stock and the object selected by the user. */,
                AssignMethodCircular/** User specified diameter, creates round
                                                                               space reservation stock. */,
                AssignMethodRectangular/** User specified values, creates rectangular
                                                                               space reservation stock. */,
                AssignMethodFlatOval/** User specified values, creates flat_oval 
                                                                                   space reservation stock. */,
                AssignMethodSpecifiedStock/** Stock selected from Specify Item dialog */
            };

            private: PathStockPreferenceBuilderImpl * m_pathstockpreferencebuilder_impl;
            private: friend class  _PathStockPreferenceBuilderBuilder;
            protected: PathStockPreferenceBuilder();
            public: ~PathStockPreferenceBuilder();
            /**Returns  the type of stock being assigned. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignStockType StockType
            (
            );
            /**Sets  the type of stock being assigned. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetStockType
            (
                NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignStockType stockType /** stock type */ 
            );
            /**Returns  the type of stock being assigned. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignStockSubType StockSubType
            (
            );
            /**Sets  the type of stock being assigned. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetStockSubType
            (
                NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignStockSubType stockType /** stock type */ 
            );
            /**Returns  the method to determine which stock to assign. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethod AssignStockMethod
            (
            );
            /**Sets  the method to determine which stock to assign. 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetAssignStockMethod
            (
                NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethod method /** method */ 
            );
            /**Returns  the start object to use for the 
                        @link NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFromStartObject NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFromStartObject@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::NXObject * StartObject
            (
            );
            /**Sets  the start object to use for the 
                        @link NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFromStartObject NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFromStartObject@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetStartObject
            (
                NXOpen::NXObject * startObject /** start object */ 
            );
            /**Returns  the diameter value to use for the 
                        @link NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodCircular NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodCircular@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Expression * Diameter
            (
            );
            /**Sets  the diameter value to use for the 
                        @link NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodCircular NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodCircular@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetDiameter
            (
                NXOpen::Expression * diameter /** diameter */ 
            );
            /**Returns  the height value to use for the  @link 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodRectangular 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodRectangular@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Expression * RectangularHeight
            (
            );
            /**Returns  the Width value to use for the  @link 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodRectangular 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodRectangular@endlink  
                        method of stock assignment    
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Expression * RectangularWidth
            (
            );
            /**Returns  the height value to use for the  @link 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFlatOval 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFlatOval@endlink  
                        method of stock assignment.  
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Expression * FlatOvalHeight
            (
            );
            /**Returns  the Width value to use for the  @link 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFlatOval 
                        NXOpen::MechanicalRouting::PathStockPreferenceBuilder::AssignMethodFlatOval@endlink  
                        method of stock assignment    
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Expression * FlatOvalWidth
            (
            );
            /** Sets the file specification of the part to place 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetFileSpecificationOfStockToPlace
            (
                const NXString & filename /** filename */ 
            );
            /** Sets the file specification of the part to place 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            void SetFileSpecificationOfStockToPlace
            (
                const char * filename /** filename */ 
            );
            /** Sets the identifier of the classification object associated with the part to place 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetClassificationObjectIdentifier
            (
                const NXString & classificationObjectId /** classificationobjectid */ 
            );
            /** Sets the identifier of the classification object associated with the part to place 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            void SetClassificationObjectIdentifier
            (
                const char * classificationObjectId /** classificationobjectid */ 
            );
            /** Validate whether the inputs to the component are sufficient for 
                        commit to be called.  If the component is not in a state to commit
                        then an exception is thrown.  For example, if the component requires
                        you to set some property, this method will throw an exception if
                        you haven't set it.  This method throws a not-yet-implemented
                        NXException for some components.
                     @return  Was self validation successful 
             <br>  Created in NX3.0.1.  <br>  
             <br> License requirements : None */
            public: virtual bool Validate
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
