#ifndef NXOpen_MECHANICALROUTING_ASSIGNCORNERBUILDER_HXX_INCLUDED
#define NXOpen_MECHANICALROUTING_ASSIGNCORNERBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MechanicalRouting_AssignCornerBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/MechanicalRouting_AssignCornerBuilder.hxx>
#include <NXOpen/MechanicalRouting_BendCornerTypeBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Routing_RouteObjectCollector.hxx>
#include <NXOpen/libnxopencpp_mechanicalrouting_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MechanicalRouting
    {
        class AssignCornerBuilder;
    }
    class Builder;
    namespace MechanicalRouting
    {
        class BendCornerTypeBuilder;
    }
    namespace Routing
    {
        class RouteObjectCollector;
    }
    namespace MechanicalRouting
    {
        class _AssignCornerBuilderBuilder;
        class AssignCornerBuilderImpl;
        /** Builder class for Assign Corner which creates corner <br> To create a new instance of this class, use @link NXOpen::MechanicalRouting::BuilderFactory::CreateAssignCornerBuilder  NXOpen::MechanicalRouting::BuilderFactory::CreateAssignCornerBuilder @endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        BendCornerSettings.Method </td> <td> 
         
        Radius </td> </tr> 

        <tr><td> 
         
        BendCornerSettings.Radius.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        <tr><td> 
         
        BendCornerSettings.RatioToDiameter.Value </td> <td> 
         
        0 (millimeters part), 0 (inches part) </td> </tr> 

        </table>  

         <br>  Created in NX11.0.0.  <br>  
        */
        class NXOPENCPP_MECHANICALROUTINGEXPORT  AssignCornerBuilder : public NXOpen::Builder
        {
            /** Defines the corner types. None,Miter and Bend. */
            public: enum CornerType
            {
                CornerTypeNone/** none */ ,
                CornerTypeBend/** bend */ ,
                CornerTypeMiter/** miter */ 
            };

            private: AssignCornerBuilderImpl * m_assigncornerbuilder_impl;
            private: friend class  _AssignCornerBuilderBuilder;
            protected: AssignCornerBuilder();
            public: ~AssignCornerBuilder();
            /**Returns  the assign corner type
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::MechanicalRouting::AssignCornerBuilder::CornerType Type
            (
            );
            /**Sets  the assign corner type
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: void SetType
            (
                NXOpen::MechanicalRouting::AssignCornerBuilder::CornerType type /** type */ 
            );
            /**Returns  the routing control points collector 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::Routing::RouteObjectCollector * ControlPointSelection
            (
            );
            /**Returns  the bend corner block 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : routing_base ("Routing Basic") */
            public: NXOpen::MechanicalRouting::BendCornerTypeBuilder * BendCornerSettings
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
