#ifndef NXOpen_MFG_MLP_PROCESSPLAN_HXX_INCLUDED
#define NXOpen_MFG_MLP_PROCESSPLAN_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Mfg_Mlp_ProcessPlan.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/libmfgmlpopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Mfg
    {
        namespace Mlp
        {
            class ProcessPlan;
        }
    }
    class NXObject;
    namespace Mfg
    {
        namespace Mlp
        {
            class _ProcessPlanBuilder;
            class ProcessPlanImpl;

            /// \cond NX_NO_DOC 
            /** Represents a Machining Line Planner process plan  <br> This is an abstract class, and cannot be instantiated.  <br> 
             <br>  Created in NX11.0.0.  <br>  
            */
            class MFGMLPOPENCPPEXPORT  ProcessPlan : public NXOpen::NXObject
            {
                private: ProcessPlanImpl * m_processplan_impl;
                private: friend class  _ProcessPlanBuilder;
                protected: ProcessPlan();
                public: ~ProcessPlan();
            };

            /// \endcond 
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
