#ifndef NXOpen_MOTION_MOTIONMANAGER_HXX_INCLUDED
#define NXOpen_MOTION_MOTIONMANAGER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Motion_MotionManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_motion_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Motion
    {
        class MotionManager;
    }
    class Part;
    namespace Motion
    {
        class AdoptionPairCollection;
    }
    namespace Motion
    {
        class BodyContactCollection;
    }
    namespace Motion
    {
        class BushingCollection;
    }
    namespace Motion
    {
        class ControlInputCollection;
    }
    namespace Motion
    {
        class ControlOutputCollection;
    }
    namespace Motion
    {
        class CouplerCollection;
    }
    namespace Motion
    {
        class CurveContactCollection;
    }
    namespace Motion
    {
        class CurveOnCurveCollection;
    }
    namespace Motion
    {
        class DamperCollection;
    }
    namespace Motion
    {
        class FlexBodyCollection;
    }
    namespace Motion
    {
        class GeneralCouplerCollection;
    }
    namespace Motion
    {
        class GraphManager;
    }
    namespace Motion
    {
        class JointCollection;
    }
    namespace Motion
    {
        class JointDriverCollection;
    }
    namespace Motion
    {
        class LinkCollection;
    }
    namespace Motion
    {
        class LinkDriverCollection;
    }
    namespace Motion
    {
        class LoadTransferCollection;
    }
    namespace Motion
    {
        class MechatronicsCollection;
    }
    namespace Motion
    {
        class MotionSensorCollection;
    }
    namespace Motion
    {
        class MotionSolutionCollection;
    }
    namespace Motion
    {
        class PMDCMotorCollection;
    }
    namespace Motion
    {
        class PlantInputCollection;
    }
    namespace Motion
    {
        class PlantOutputCollection;
    }
    namespace Motion
    {
        class PointOnCurveCollection;
    }
    namespace Motion
    {
        class PointOnSurfaceCollection;
    }
    namespace Motion
    {
        class ResultMeasureCollection;
    }
    namespace Motion
    {
        class RoadCollection;
    }
    namespace Motion
    {
        class ScalarForceCollection;
    }
    namespace Motion
    {
        class ScalarTorqueCollection;
    }
    namespace Motion
    {
        class SignalChartCollection;
    }
    namespace Motion
    {
        class SpringCollection;
    }
    namespace Motion
    {
        class TireCollection;
    }
    namespace Motion
    {
        class TirePropertyBasicCollection;
    }
    namespace Motion
    {
        class TirePropertyCdCollection;
    }
    namespace Motion
    {
        class TirePropertyFtCollection;
    }
    namespace Motion
    {
        class TirePropertyMotorcycleCollection;
    }
    namespace Motion
    {
        class TirePropertyNonInertialCollection;
    }
    namespace Motion
    {
        class TirePropertyTnoCollection;
    }
    namespace Motion
    {
        class VectorForceCollection;
    }
    namespace Motion
    {
        class VectorTorqueCollection;
    }
    namespace Motion
    {
        class MotionManagerImpl;
        /** A manager to deal with all motion objects  <br> To obtain an instance of this class, refer to @link NXOpen::Part  NXOpen::Part @endlink  <br> 
         <br>  Created in NX5.0.0.  <br>  
        */
        class NXOPENCPP_MOTIONEXPORT  MotionManager
        {
            private: MotionManagerImpl * m_motionmanager_impl;
            private: NXOpen::Part* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit MotionManager(NXOpen::Part *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~MotionManager();


            /** Returns the @link Motion::JointCollection  Motion::JointCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::JointCollection *Joints();
            /** Returns the @link Motion::LinkCollection  Motion::LinkCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::LinkCollection *Links();
            /** Returns the @link Motion::JointDriverCollection Motion::JointDriverCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::JointDriverCollection *JointDrivers();
            /** Returns the @link Motion::ScalarForceCollection  Motion::ScalarForceCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::ScalarForceCollection *ScalarForces();
            /** Returns the @link Motion::ScalarTorqueCollection  Motion::ScalarTorqueCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::ScalarTorqueCollection *ScalarTorques();
            /** Returns the @link Motion::GraphManager Motion::GraphManager@endlink  for this part
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::GraphManager *Graphs();
            /** Returns the @link  Motion::SignalChartCollection   Motion::SignalChartCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::SignalChartCollection *SignalCharts();
            /** Returns the @link  Motion::PMDCMotorCollection   Motion::PMDCMotorCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::PMDCMotorCollection *PMDCMotors();
            /** Returns the @link Motion::MotionSolutionCollection Motion::MotionSolutionCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::MotionSolutionCollection *MotionSolutions();
            /** Returns the @link Motion::BodyContactCollection Motion::BodyContactCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::BodyContactCollection *BodyContacts();
            /** Returns the @link Motion::CurveContactCollection Motion::CurveContactCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::CurveContactCollection *CurveContacts();
            /** Returns the @link Motion::PointOnSurfaceCollection Motion::PointOnSurfaceCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::PointOnSurfaceCollection *PointOnSurfaces();
            /** Returns the @link Motion::PointOnCurveCollection Motion::PointOnCurveCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::PointOnCurveCollection *PointOnCurves();
            /** Returns the @link Motion::CurveOnCurveCollection Motion::CurveOnCurveCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::CurveOnCurveCollection *CurveOnCurves();
            /** Returns the @link Motion::VectorForceCollection Motion::VectorForceCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::VectorForceCollection *VectorForces();
            /** Returns the @link Motion::VectorTorqueCollection Motion::VectorTorqueCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::VectorTorqueCollection *VectorTorques();
            /** Returns the @link Motion::CouplerCollection Motion::CouplerCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::CouplerCollection *Couplers();
            /** Returns the @link Motion::MotionSensorCollection Motion::MotionSensorCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::MotionSensorCollection *MotionSensors();
            /** Returns the @link Motion::PlantOutputCollection Motion::PlantOutputCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::PlantOutputCollection *PlantOutputs();
            /** Returns the @link Motion::PlantInputCollection Motion::PlantInputCollection@endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::PlantInputCollection *PlantInputs();
            /** Returns the @link Motion::SpringCollection  Motion::SpringCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::SpringCollection *Springs();
            /** Returns the @link Motion::DamperCollection  Motion::DamperCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::DamperCollection *Dampers();
            /** Returns the @link Motion::BushingCollection  Motion::BushingCollection @endlink  belonging to this part 
             <br>  Created in NX3.0.0.  <br>  
            */
            public: NXOpen::Motion::BushingCollection *Bushings();
            /** Returns the @link Motion::FlexBodyCollection  Motion::FlexBodyCollection @endlink  belonging to this part 
             <br>  Created in NX7.5.0.  <br>  
            */
            public: NXOpen::Motion::FlexBodyCollection *FlexBodies();
            /** Returns the @link Motion::GeneralCouplerCollection  Motion::GeneralCouplerCollection @endlink  belonging to this part 
             <br>  Created in NX7.5.0.  <br>  
            */
            public: NXOpen::Motion::GeneralCouplerCollection *GeneralCouplers();
            /** Returns the @link Motion::LoadTransferCollection  Motion::LoadTransferCollection @endlink  belonging to this part 
             <br>  Created in NX9.0.0.  <br>  
            */
            public: NXOpen::Motion::LoadTransferCollection *LoadTransfers();
            /** Returns the @link NXOpen::Motion::AdoptionManager  NXOpen::Motion::AdoptionManager @endlink belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::AdoptionPairCollection *AdoptionPairs();
            /** Returns the @link Motion::ResultMeasureCollection  Motion::ResultMeasureCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::ResultMeasureCollection *ResultMeasures();
            /** Returns the @link Motion::RoadCollection Motion::RoadCollection@endlink  for this part
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::RoadCollection *Roads();
            /** Returns the @link Motion::ControlInputCollection  Motion::ControlInputCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::ControlInputCollection *ControlInputs();
            /** Returns the @link Motion::TireCollection  Motion::TireCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TireCollection *Tires();
            /** Returns the @link Motion::TirePropertyFtCollection  Motion::TirePropertyFtCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyFtCollection *TirePropertiesFt();
            /** Returns the @link Motion::TirePropertyTnoCollection  Motion::TirePropertyTnoCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyTnoCollection *TirePropertiesTno();
            /** Returns the @link Motion::TirePropertyCdCollection  Motion::TirePropertyCdCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyCdCollection *TirePropertiesCd();
            /** Returns the @link Motion::ControlOutputCollection  Motion::ControlOutputCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::ControlOutputCollection *ControlOutputs();
            /** Returns the @link Motion::MechatronicsCollection  Motion::MechatronicsCollection @endlink belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::MechatronicsCollection *Mechatronics();
            /** Returns the @link Motion::LinkDriverCollection Motion::LinkDriverCollection@endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::LinkDriverCollection *LinkDrivers();
            /** Returns the @link Motion::TirePropertyBasicCollection  Motion::TirePropertyBasicCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyBasicCollection *TirePropertiesBasic();
            /** Returns the @link Motion::TirePropertyMotorcycleCollection  Motion::TirePropertyMotorcycleCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyMotorcycleCollection *TirePropertiesMotorcycle();
            /** Returns the @link Motion::TirePropertyNonInertialCollection  Motion::TirePropertyNonInertialCollection @endlink  belonging to this part 
             <br>  Created in NX11.0.0.  <br>  
            */
            public: NXOpen::Motion::TirePropertyNonInertialCollection *TirePropertiesNonInertial();
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
